#ifndef INT_CODES_H
#define INT_CODES_H

#define TF_ADMM 0
#define TF_PRIMALDUAL_IP 1
#define TF_PROJECTED_NEWTON 2

#define FAMILY_GAUSSIAN 0
#define FAMILY_LOGISTIC 1
#define FAMILY_POISSON 2

#endif