setClass("glmgen",
         representation = representation(y = "numeric",
                                         lambda = "numeric",
                                         beta = "matrix",
                                         family = "character",
                                         method = "character",
                                         n = "integer",
                                         p = "integer",
                                         m = "integer",
                                         obj = "numeric",
                                         call = "call"),
         prototype = prototype(y = NA_real_,
                               lambda = NA_real_,
                               beta = matrix(NA_real_),
                               family = NA_character_,
                               method = NA_character_,
                               n = 0L,
                               p = 0L,
                               m = 0L,
                               obj = NA_real_,
                               call = call("glmgen")),
         sealed = TRUE)

setClass("trendfilter",
         representation = representation(y = "numeric",
                                         x = "numeric",
                                         k = "integer",
                                         lambda = "numeric",
                                         beta = "matrix",
                                         family = "character",
                                         method = "character",
                                         n = "integer",
                                         p = "integer",
                                         m = "integer",
                                         obj = "numeric",
                                         call = "call"),
         prototype = prototype(y = NA_real_,
                               x = NA_real_,
                               k = NA_integer_,
                               lambda = NA_real_,
                               beta = matrix(NA_real_),
                               family = NA_character_,
                               method = NA_character_,
                               n = 0L,
                               p = 0L,
                               m = 0L,
                               obj = NA_real_,
                               call = call("glmgen")),
         contains = "glmgen",
         sealed = TRUE)

setClass("summary.glmgen",
         representation = representation(summary = "matrix"),
         prototype = prototype(summary = matrix(NA_real_)),
         sealed = TRUE)


